### ISSUE TITLE
Conflict with cocoapods 1.1.1 (bump to xcodeproj > 1.3.3 vesion

### ISSUE THREAD

**Issue by PaulTaykalo** [faithfracture/update_provisioning_profile_specifier#3]
At the moment the latest cocoapods depends on `xcodeproj >= 1.3.3`
Is there any need to use xcodeproj 1.3.1 ?

**Comment by faithfracture** [comment]
1.3.2 was broken when used with other actions that used it (it wasn't executing on the property directory). I haven't tried it with 1.3.3 yet though. I've been meaning to check if it had been updated & change that requirement though. I'll check it out and update the requirement if it's fixed.

**Comment by PaulTaykalo** [comment]
Also is there any additional setup needed to run tests? It seems that tests don't see any .xcodeproj files

**Comment by faithfracture** [comment]
Ha, tests, good one.

I didn't actually write a sample app for this plugin. I just created it with the fastlate new_plugin command, which generates the project structure. All the documentation and other stuff was auto-created. I was kind of in a bind when I wrote this, so I was just happy that it worked. (I should probably actually finish developing the rest of that stuff...)

**Comment by faithfracture** [comment]
Updated to >= 1.3.3
