### ISSUE TITLE
If two targets have similar names, the PROVISIONING_PROFILE_SPECIFIER is updated in both

### ISSUE THREAD

**Issue by PawelPalkaPerform** [faithfracture/update_provisioning_profile_specifier#7]
Hi There

Example:

```
App Name 
App Name NSE (this is app extension)
```

Usage:

```
update_provisioning_profile_specifier(target: "App Name",
                                                               new_specifier: "com.appname.sth")
```

Result:

Both targets have the same provisioning :-(
How to solve this issue?

**Comment by faithfracture** [comment]
Just to clarify, you have two targets. One named "App Name" and one named "App Name NSE". When you run `update_provisioning_profile_specifier(target: "App Name", new_specifier: "com.appname.sth")`, the PROVISIONING_PROFILE_SPECIFIER for both targets is being updated to "com.appname.sth"?

As it is right now, this plugin uses Ruby's `match` function to compare the given target name with the targets found in the Xcode project - meaning if you have two targets with the same characters in it it will match both ("My App" and "My App Extension", for example).

I'll need to update the plugin to account for this, but you should be able to work around it by renaming one of your targets to something else. For example, you could use "App Name" for the main target and "App NSE" for the app extension target.

Unfortunately I can't think of another way around this right now without updating the plugin, which I will do but it's going to be a few days before I can get around to it.

**Comment by PawelPalkaPerform** [comment]
Yes, this is exactly the case. Still can't rename targets, as I work with few teams around the world on this project and renaming of targets is not in option.

Anyway, thank you for response :)

**Comment by faithfracture** [comment]
Sorry that took so long to get to.
